### PR TITLE
Add new constructor parameter to choose a custom EventSource implementation

### PR DESCRIPTION
**Pull request by tbl0605**
Hi,
I'm currently using this library with a custom EventSource library called [eventsource](https://github.com/EventSource/eventsource) (and it works great), but I have first to override the EventSource class provided by the browser by doing:
````
import ReconnectingEventSource from 'reconnecting-eventsource';
import { default as CustomEventSource } from 'eventsource';

// NB: "globalThis.EventSource = CustomEventSource;" would also work.
window.EventSource = CustomEventSource;

new ReconnectingEventSource('myUrl', {});
````

It would actually be great to be able to provide the custom EventSource class as a third parameter to the constructor, for example:
````
import ReconnectingEventSource from 'reconnecting-eventsource';
import { default as CustomEventSource } from 'eventsource';

new ReconnectingEventSource('myUrl', {}, CustomEventSource);
````

My patch is doing this, assuming that custom EventSource classes can be instantiated the same way as the original EventSource class. 

Thierry.

### CODE REVIEW

**Comment by harmony7** [comment]
I would like to suggest a different way to implement this, rather than modifying the constructor signature.

The second parameter to the constructor is a custom initialization object that adds the value `max_retry_time`
in addition to the `withCredentials` that is provided in the original impelmentation.

Since we are already extending this object and adding custom configurations, I would like to suggest the
addition of `eventSourceClass` as a custom configuration on this second parameter in the same way.

**Comment by tbl0605** [comment]
> Since we are already extending this object and adding custom configurations, I would like to suggest the addition of `eventSourceClass` as a custom configuration on this second parameter in the same way.

Hi @harmony7,
I hope my patch looks better now ^^

**Comment by tbl0605** [comment]
Hi @harmony7,
I'm still hoping you could have a look at my patch :)
Thank you!

**Comment by harmony7** [comment]
Okay! I'll have a chance to look at this again on the weekend.

**Comment by tbl0605** [comment]
Thank you a lot! :) Feel free to rework my patch, so it can be merged asap.
In my case, I'm using your library with my patch since one month without any problem.

**Review by harmony7 — APPROVED** [review]
Looks good

**Pull request merged**
